services:
  ultima_db:
    image: postgres:17.10
    container_name: ultima_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  ultima_web:
    build: .
    container_name: ultima_web
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG:-False}
    ports:
      - "8000:8000"
    depends_on:
      - ultima_db

  ultima_tunnel:
    image: cloudflare/cloudflared:latest
    container_name: ultima_tunnel
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - ultima_web

  ultima_backup:
    image: prodrigestivill/postgres-backup-local:17
    container_name: ultima_backup
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=ultima_db
      - POSTGRES_CLUSTER=true
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_BACKUP_PRUNE_DAYSS=7
      - SCHEDULE=@daily
    volumes:
      - ./backups:/backups
    depends_on:
      - ultima_db

volumes:
  postgres_data: