# Generated by Django 6.0.6 on 2026-06-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_type', models.CharField(choices=[('TR', 'Transfer'), ('THB', 'Thai Baht'), ('USD', 'US Dollar'), ('CARD', 'Card'), ('GC', 'Guide Credit')], default='THB', max_length=4)),
            ],
        ),
    ]
