# Generated by Django 6.0.6 on 2026-06-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
