# Generated by Django 6.0.6 on 2026-07-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_comment_author_alter_sale_salesman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='group_identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
