# Generated by Django 6.0.6 on 2026-06-21 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_sale_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at']},
        ),
    ]
