# Generated by Django 6.0.6 on 2026-07-08 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_presentation_group_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='finance.sale'),
        ),
    ]
