# Generated by Django 6.0.6 on 2026-07-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_outboxevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='partner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='partner_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
