# Generated by Django 6.0.6 on 2026-08-09 04:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_sale_client_rate_sale_partner_name_sale_partner_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='transfer_amount_rub',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
