# Generated by Django 6.0.6 on 2026-08-09 05:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_sale_transfer_amount_rub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='transfer_amount_rub',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=14),
        ),
    ]
